name: time_converter
description: You can change the time to the format you want.
version: 0.0.1
homepage: https://github.com/tazan83/time_converter.git

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dev_dependencies:
  flutter_lints: ^1.0.0
